spring.output.ansi.enabled=always

spring.application.name=multi_module

spring.datasource.url=jdbc:postgresql://localhost:5432/repertoire
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

spring.main.banner-mode=off

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.xml